import React from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { EVENT_CATEGORIES } from '../services/storage';
const months = ['leden', 'únor', 'březen', 'duben', 'květen', 'červen', 'červenec', 'srpen', 'září', 'říjen', 'listopad', 'prosinec']; const weekdays = ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'];
const dateString = (year, month, day) => `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
export const CalendarGrid = ({ currentDate, onDateChange, events, selectedUserFilter, onUserFilterChange, onSelectEvent, onDayClick, users }) => {
  const year = currentDate.getFullYear(), month = currentDate.getMonth(), days = new Date(year, month + 1, 0).getDate(), offset = (new Date(year, month, 1).getDay() + 6) % 7, today = new Date().toISOString().slice(0, 10);
  const visible = selectedUserFilter ? events.filter(event => event.userId === selectedUserFilter) : events;
  return <section className="calendar-card glass-card"><div className="calendar-header"><div><p className="eyebrow">KALENDÁŘ</p><h2 className="month-title">{months[month]} <span>{year}</span></h2></div><div className="calendar-controls"><button className="plain-btn" onClick={() => onDateChange(new Date())}>Dnes</button><div className="nav-buttons"><button className="icon-button" onClick={() => onDateChange(new Date(year, month - 1, 1))}><ChevronLeft size={18} /></button><button className="icon-button" onClick={() => onDateChange(new Date(year, month + 1, 1))}><ChevronRight size={18} /></button></div></div></div>
    <div className="people-filter"><button className={!selectedUserFilter ? 'active' : ''} onClick={() => onUserFilterChange(null)}>Všichni</button>{users.map(user => <button key={user.id} className={selectedUserFilter === user.id ? 'active' : ''} onClick={() => onUserFilterChange(selectedUserFilter === user.id ? null : user.id)}><i style={{ background: user.color }} />{user.username}</button>)}</div>
    <div className="weekdays-grid">{weekdays.map((day, index) => <span className={index > 4 ? 'weekend' : ''} key={day}>{day}</span>)}</div><div className="days-grid">{Array.from({ length: offset }).map((_, index) => <div className="day-blank" key={index} />)}{Array.from({ length: days }, (_, index) => { const day = index + 1, date = dateString(year, month, day), items = visible.filter(item => date >= item.startDate && date <= item.endDate); return <button className={`day-cell ${date === today ? 'today' : ''}`} key={date} onClick={() => onDayClick(date)}><span className="day-number">{day}</span><span className="day-events-container">{items.slice(0, 2).map(item => <span className="event-bar" key={item.id} onClick={event => { event.stopPropagation(); onSelectEvent(item); }} style={{ '--event': EVENT_CATEGORIES[item.category]?.color || '#69774c', '--event-bg': EVENT_CATEGORIES[item.category]?.bg || '#eef3ec' }}><i style={{ background: item.userColor }} />{item.userName}</span>)}{items.length > 2 && <small>+ {items.length - 2}</small>}</span></button>; })}</div></section>;
};
